attempt to build docs too

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,3 +26,20 @@ jobs:
     - name: Run Tox
       shell: bash -l {0}
       run: tox
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/alexjbest/cluster-pictures.git --branch gh-pages --single-branch gh-pages
+        cp -r .tox/docs/tmp/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
